- name: Query OMDb API and create Excel
  become: false
  hosts: all
  gather_facts: false
  vars_files:
    - vars/secrets.yml
  vars:
    search_term: "Matrix"
    output_file: "movies_results.xlsx"
    log_file: "ansible_api_excel.log"
    ts: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%SZ') }}"

  tasks:
    - name: Check Host Connectivity
      block:
        - name: Check host connectivity
          ansible.builtin.wait_for_connection:
            timeout: 10

        - name: Log Host Reachable
          ansible.builtin.lineinfile:
            path: "{{ log_file }}"
            line: "[{{ ts }}][SUCCESS] Host {{ inventory_hostname }} is reachable"
            create: true
            mode: "0644"
          delegate_to: localhost
          changed_when: false

        - name: Set connectivity flag
          ansible.builtin.set_fact:
            host_is_reachable: true

      rescue:
        - name: Log Host Unreachable
          ansible.builtin.lineinfile:
            path: "{{ log_file }}"
            line: "[{{ ts }}][WARNING] Host {{ inventory_hostname }} is unreachable, continuing with API process"
            create: true
            mode: "0644"
          delegate_to: localhost
          changed_when: false

        - name: Set connectivity flag
          ansible.builtin.set_fact:
            host_is_reachable: false

    - name: API Process
      block:
        - name: Query OMDb API
          ansible.builtin.uri:
            url: "http://www.omdbapi.com/?apikey={{ omdb_api_key }}&s={{ search_term }}"
            return_content: true
          register: api_res
          delegate_to: localhost

        - name: Validate API Response
          ansible.builtin.assert:
            that:
              - api_res.json.Response == "True"
            fail_msg: "API Error: {{ api_res.json.Error | default('Unknown') }}"

        - name: Create Excel
          ditra.cisco.one_sheet_excel:
            create: true
            data: "{{ api_res.json.Search }}"
            file: "{{ output_file }}"
            operation: write
            path: "."
            sheet_name: "movies"
          delegate_to: localhost

        - name: Log Success
          ansible.builtin.lineinfile:
            path: "{{ log_file }}"
            line: "[{{ ts }}][INFO] Host {{ inventory_hostname }} - Success: {{ search_term }} -> {{ output_file }}"
            create: true
            mode: "0644"
          delegate_to: localhost
          changed_when: false

      rescue:
        - name: Log Failure
          ansible.builtin.lineinfile:
            path: "{{ log_file }}"
            line: "[{{ ts }}][ERROR] Host {{ inventory_hostname }} - Error en proceso API/Excel"
            create: true
            mode: "0644"
          delegate_to: localhost
          changed_when: false
